[package]
authors = ["adoo <Adoo@outlook.com>"]
edition = "2021"
name = "gpu"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
algo = {path = "../algo"}
futures = {version = "0.3.21", optional = true}
guillotiere = "0.6.0"
lyon_tessellation = "1.0.1"
painter = {path = "../painter"}
raw-window-handle = {version = "0.4.2", optional = true}
rayon = "1.5.1"
text = {path = "../text"}
wgpu = {version = "0.12.0", optional = true}
zerocopy = "0.6.1"

[dev-dependencies]
colored = "1.9.3"
env_logger = "0.7.1"
futures = "0.3.5"
png = "0.17.5"
ribir = {path = "../ribir"}
winit = "0.26.1"

[features]
ui_window = []
wgpu_gl = ["wgpu", "raw-window-handle", "futures"]

[[example]]
name = "wgpu-hello"
required-features = ["wgpu_gl"]

[[test]]
harness = false
name = "main_thread"
path = "src/tests/main_threads.rs"
