[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "ribir_gpu"
readme.workspace = true
repository = "https://github.com/RibirX/Ribir/gpu"
version.workspace = true

[dependencies]
futures = {workspace = true, optional = true}
guillotiere.workspace = true
lyon_tessellation.workspace = true
raw-window-handle = {workspace = true, optional = true}
rayon.workspace = true
ribir_algo = {path = "../algo", version = "0.0.0"}
ribir_painter = {path = "../painter", version = "0.0.0"}
ribir_text = {path = "../text", version = "0.0.0"}
wgpu = {workspace = true, optional = true}
zerocopy.workspace = true

[dev-dependencies]
colored.workspace = true
env_logger.workspace = true
futures.workspace = true
image.workspace = true
ribir = {path = "../ribir", version = "*"}
winit.workspace = true

[features]
test_gpu = []
ui_window = []
wgpu_gl = ["wgpu", "raw-window-handle", "futures"]

[[example]]
name = "wgpu-hello"
required-features = ["wgpu_gl"]

[[test]]
harness = false
name = "main_thread"
path = "src/tests/main_threads.rs"
