[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "ribir_gpu"
readme.workspace = true
repository = "https://github.com/RibirX/Ribir/gpu"
version.workspace = true

[dependencies]
futures = {version = "0.3.21", optional = true}
guillotiere = "0.6.0"
lyon_tessellation = "1.0.1"
raw-window-handle = {version = "0.5.0", optional = true}
rayon = "1.5.1"
ribir_algo = {path = "../algo", version = "0.0.0"}
ribir_painter = {path = "../painter", version = "0.0.0"}
ribir_text = {path = "../text", version = "0.0.0"}
wgpu = {version = "0.15.1", optional = true}
zerocopy = "0.6.1"

[dev-dependencies]
colored = "1.9.3"
env_logger = "0.7.1"
futures = "0.3.5"
png = "0.17.5"
ribir = {path = "../ribir", version = "*"}
winit = "0.28.1"

[features]
test_gpu = []
ui_window = []
wgpu_gl = ["wgpu", "raw-window-handle", "futures"]

[[example]]
name = "wgpu-hello"
required-features = ["wgpu_gl"]

[[test]]
harness = false
name = "main_thread"
path = "src/tests/main_threads.rs"
