[package]
authors = ["adoo <Adoo@outlook.com>"]
categories = ["gui"]
description = "Ribir is a framework for building modern native/wasm cross-platform user interface applications."
documentation = "https://ribir.org/docs"
edition = "2021"
homepage = "https://ribir.org"
keywords = ["gui", "ui", "declarative", "compose-ui"]
license = "MIT"
name = "ribir_gpu"
readme = "README.md"
repository = "https://github.com/RibirX/Ribir/algo"
version = "0.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = {version = "0.3.21", optional = true}
guillotiere = "0.6.0"
lyon_tessellation = "1.0.1"
raw-window-handle = {version = "0.5.0", optional = true}
rayon = "1.5.1"
ribir_algo = {path = "../algo", version = "0.0.0"}
ribir_painter = {path = "../painter", version = "0.0.0"}
ribir_text = {path = "../text", version = "0.0.0"}
wgpu = {version = "0.15.1", optional = true}
zerocopy = "0.6.1"

[dev-dependencies]
colored = "1.9.3"
env_logger = "0.7.1"
futures = "0.3.5"
png = "0.17.5"
ribir = {path = "../ribir", version = "*"}
winit = "0.28.1"

[features]
test_gpu = []
ui_window = []
wgpu_gl = ["wgpu", "raw-window-handle", "futures"]

[[example]]
name = "wgpu-hello"
required-features = ["wgpu_gl"]

[[test]]
harness = false
name = "main_thread"
path = "src/tests/main_threads.rs"
