[workspace]
members = [
  "core",
  "gpu",
  "painter",
  "widget_derive",
  "widget_derive/builtin",
  "algo",
  "text",
  "animation",
]
resolver = "2"

[profile.bench]
debug = true

[profile.release]
debug = true
