[workspace]
members = [
  "core",
  "gpu",
  "painter",
  "macros",
  "macros/builtin",
  "algo",
  "text",
  "widgets",
  "ribir",
  "tests",
]
resolver = "2"

[profile.bench]
debug = true

[profile.release]
debug = true

[workspace.package]
authors = ["adoo <Adoo@outlook.com>"]
categories = ["gui"]
description = "Ribir is a framework for building modern native/wasm cross-platform user interface applications."
documentation = "https://ribir.org/docs"
edition = "2021"
homepage = "https://ribir.org"
keywords = ["gui", "ui", "declarative", "compose-ui"]
license = "MIT"
readme = "README.md"
version = "0.0.0"

[workspace.dependencies]
ahash = "0.8.3"
bitflags = "2.0.0"
bitflags-serde-legacy = "0.1.0"
blake3 = "1.3.3"
colored = "2.0.0"
derive_more = "0.99.17"
env_logger = "0.7.1"
euclid = "0.22.6"
fontdb = "0.13.0"
futures = "0.3.26"
guillotiere = "0.6.0"
indextree = "4.5.0"
Inflector = "0.11.4"
lazy_static = "1.4.0"
log = "0.4.14"
lyon_algorithms = "1.0.1"
lyon_geom = "1.0.1"
lyon_path = "1.0.1"
lyon_tessellation = "1.0.1"
ordered-float = "3.4.0"
palette = "0.6.1"
image = "0.24.5"
proc-macro2 = "1.0.36"
quote = "1.0.16"
raw-window-handle = "0.5.0"
rayon = "1.5.1"
rctree ="0.5.0"
rxrust = "1.0.0-beta.1"
rustybuzz = "0.7.0"
serde = "1.0"
serde_json = "1.0.82"
smallvec = "1.8.0"
syn = "1.0.109"
unicode-bidi = "0.3.7"
unicode-script = "0.5.4"
unicode-segmentation = "1.9.0"
usvg = "0.29.0"
wgpu = "0.15.1"
winit = "0.28.1"
zerocopy = "0.6.1"
