[workspace]
members = [
  "algo",
  "app",
  "core",
  "geometry",
  "gpu",
  "macros",
  "macros/builtin",
  "painter",
  "ribir",
  "text",
  "widgets",
  "winit",
]
resolver = "2"

[profile.bench]
debug = true

[profile.release]
debug = true
