[workspace]
members = [
  "core",
  "gpu",
  "painter",
  "macros",
  "macros/builtin",
  "algo",
  "text",
  "widgets",
  "app_winit",
  "ribir",
]
resolver = "2"

[profile.bench]
debug = true

[profile.release]
debug = true
