[package]
name = "cli"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
xshell = "0.2.3"
clap = {version = "4.5.4", features = ["cargo", "derive"] }
anyhow = { version = "1.0" }
fs_extra = "1.3.0"
