[package]
authors = ["adoo <Adoo@outlook.com>"]
edition = "2021"
name = "ribir"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
canvas = {path = "../canvas", version = "*"}
futures = "0.3.5"
indextree = "4.3.1"
lazy_static = "1.4.0"
log = "0.4.8"
rxrust = "1.0.0-alpha.2"
widget_derive = {path = "../widget_derive"}
winit = "0.24.0"

[dependencies.blake3]
features = ["rayon"]
version = "0.3.4"

[dev-dependencies]
env_logger = "0.7.1"
unit_test = {path = "../unit_test"}
