[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "ribir_core"
readme.workspace = true
repository = "https://github.com/RibirX/Ribir/core"
version.workspace = true

[dependencies]
ahash = "0.8.3"
bitflags = "2.0.0"
futures = "0.3.26"
indextree = "4.5.0"
lazy_static = "1.4.0"
log = "0.4.8"
lyon_algorithms = "1.0.1"
lyon_geom = "1.0.1"
png = {version = "0.17.3", optional = true}
ribir_algo = {path = "../algo", version = "0.0.0"}
ribir_gpu = {path = "../gpu", version = "0.0.0", features = ["wgpu_gl"]}
ribir_macros = {path = "../macros", version = "0.0.0"}
ribir_painter = {path = "../painter", version = "0.0.0"}
ribir_text = {path = "../text", version = "0.0.0"}
rxrust = "1.0.0-beta.1"

smallvec = "1.8.0"
winit = "0.28.1"

[dependencies.blake3]
features = ["rayon"]
version = "1.3.3"

[features]
png = ["dep:png"]
thread-pool = [
  "futures/thread-pool",
]

[dev-dependencies]
colored = "2.0.0"
