[package]
name = "holiday"
version = "0.1.0"
authors = ["adoo <Adoo@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
herald =  "0.1.0"
indextree= "4.1.0"
rxrust = {git="https://github.com/rxRust/rxRust.git"}
bitflags = "1.2.1"
winit = "0.22.2"
canvas = {path= "../canvas", version="*"}
futures="0.3.5"
log = "0.4.8"
smallvec = "1.4.1"

[dependencies.blake3]
version = "0.3.4"
features = ["rayon"]