[package]
authors = ["adoo <Adoo@outlook.com>"]
edition = "2021"
name = "ribir_core"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.7.6"
bitflags = "1.2.1"
futures = "0.3.26"
indextree = "4.5.0"
lazy_static = "1.4.0"
log = "0.4.8"
lyon_algorithms = "1.0.1"
lyon_geom = "1.0.1"
png = {version = "0.17.3", optional = true}
ribir_algo = {path = "../algo"}
ribir_gpu = {path = "../gpu"}
ribir_macros = {path = "../macros"}
ribir_painter = {path = "../painter", version = "*"}
ribir_text = {path = "../text"}
rxrust = {path = "../../rxRust"}

smallvec = "1.8.0"
winit = "0.26.1"

[dependencies.blake3]
features = ["rayon"]
version = "0.3.4"

[features]
png = ["dep:png"]
thread-pool = [
  "futures/thread-pool",
]

[dev-dependencies]
colored = "2.0.0"
