[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "ribir_core"
readme.workspace = true
repository = "https://github.com/RibirX/Ribir/core"
version.workspace = true

[dependencies]
ahash.workspace = true
bitflags.workspace = true
blake3 = {workspace = true, features = ["rayon"]}
futures.workspace = true
indextree.workspace = true
lazy_static.workspace = true
log.workspace = true
lyon_geom.workspace = true
ribir_algo = {path = "../algo", version = "0.0.0"}
ribir_macros = {path = "../macros", version = "0.0.0"}
ribir_painter = {path = "../painter", version = "0.0.0"}
ribir_text = {path = "../text", version = "0.0.0"}
ribir_geom = {path = "../geom", version = "0.0.0"}
rxrust.workspace = true
smallvec.workspace = true
winit.workspace = true
arboard = "3.2.0"

[dev-dependencies]
colored.workspace = true

[features]
png = ["ribir_painter/png"]
thread-pool = [
  "futures/thread-pool",
]
