[package]
name = "canvas"
version = "0.1.0"
authors = ["adoo <Adoo@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.5.0"
lyon =  { git = "https://github.com/nical/lyon", version="*"}
palette = "0.5"
bytemuck = "1.2.0"
raw-window-handle = "0.3.3"
euclid = "0.20.11"
png = "0.16.3"

[dev-dependencies]
winit="0.22.1"
futures="0.3.4"

# [[test]]
# name = "wgpu_tests"
# path = "wgpu_tests/canvas.rs"
# harness = false