[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "ribir"
readme.workspace = true
repository = "https://github.com/RibirX/Ribir/ribir"
version.workspace = true

[dependencies]
once_cell.workspace = true
ribir_core = {path = "../core", version = "0.0.0"}
ribir_gpu = {path = "../gpu", version = "0.0.0"}
ribir_material = {path = "../themes/material", version = "0.0.0", optional = true}
ribir_widgets = {path = "../widgets", version = "0.0.0", optional = true}
rxrust.workspace = true
wgpu = {workspace = true, optional = true}
winit.workspace = true
arboard = "3.2.0"

[dev-dependencies]
colored.workspace = true
env_logger.workspace = true
futures.workspace = true
ribir_dev_helper = {path = "../dev-helper", version = "0.0.0"}
ribir_material = {path = "../themes/material", version = "0.0.0"}

[features]
default = ["wgpu", "widgets", "material"]
material = ["ribir_material"]
png = ["ribir_core/png"]
wgpu = ["ribir_gpu/wgpu", "dep:wgpu"]
widgets = ["ribir_widgets"]

[[test]]
harness = false
name = "single_thread"
path = "tests/timer_test.rs"
