[package]
edition = "2021"
name = "ribir"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ribir_core = {path = "../core"}
ribir_widgets = {path = "../widgets"}

[dev-dependencies]
env_logger = "0.7.1"
