[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "ribir_macros"
readme.workspace = true
repository = "https://github.com/RibirX/Ribir/macros"
version.workspace = true

[lib]
proc-macro = true

[dependencies]
Inflector = "0.11.4"
ahash = "0.8.3"
bitflags = "2.0.0"
lazy_static = "1.4.0"
proc-macro2 = "1.0.36"
quote = "1.0.16"
ribir_builtin = {path = "./builtin", version = "0.0.0"}
ribir_painter = {path = "../painter", version = "0.0.0"}
smallvec = "1.8.0"

[build-dependencies]
ribir_builtin = {path = "./builtin", version = "0.0.0"}

[dependencies.syn]
features = ["visit-mut", "full", "extra-traits"]
version = "1.0.109"
