[package]
authors = ["Adoo <Adoo@outlook.com>"]
edition = "2021"
name = "ribir_macros"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
Inflector = "0.11.4"
ahash = "0.7.6"
bitflags = "1.3.2"
builtin = {path = "./builtin"}
lazy_static = "1.4.0"
painter = {path = "../painter"}
proc-macro2 = "1.0.36"
quote = "1.0.16"
smallvec = "1.8.0"

[dev-dependencies]
ribir = {path = "../ribir"}
trybuild = "1.0.53"
winit = "0.26.1"

[build-dependencies]
builtin = {path = "./builtin"}

[dependencies.syn]
features = ["visit-mut", "full", "extra-traits"]
version = "1.0.83"
