[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "ribir_painter"
readme.workspace = true
repository = "https://github.com/RibirX/Ribir/painter"
version.workspace = true

[dependencies]
bitflags.workspace = true
bitflags-serde-legacy.workspace = true
euclid.workspace = true
log.workspace = true
lyon_algorithms.workspace = true
lyon_tessellation = {workspace = true, features = ["serialization"]}
palette = {workspace = true, features = ["serializing"]}
rctree.workspace = true
ribir_algo = {path = "../algo", version = "0.0.0"}
ribir_text = {path = "../text", version = "0.0.0"}
ribir_geom = {path = "../geom", version = "0.0.0"}
serde = {workspace = true, features = ["rc"]}
serde_json.workspace = true
usvg.workspace = true
image = {workspace = true, optional = true, default-features = false}
material-color-utilities-rs = {workspace = true}

[features]
png = ["image",  "image/png"]
