[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "ribir_painter"
readme.workspace = true
repository = "https://github.com/RibirX/Ribir/painter"
version.workspace = true

[dependencies]
bitflags = "2.0.0"
euclid = "0.22.6"
log = "0.4.17"
lyon_algorithms = "1.0.1"
lyon_tessellation = {version = "1.0.1", features = ["serialization"]}
palette = {version = "0.6.1", features = ["serializing"]}
ribir_algo = {path = "../algo", version = "0.0.0"}
ribir_text = {path = "../text", version = "0.0.0"}
serde = {version = "1.0", features = ["rc"]}
serde_json = "1.0.82"
usvg = {version = "0.29.0"}
rctree ="0.5.0"
bitflags-serde-legacy = "0.1.0"
