[package]
edition = "2021"
name = "painter"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
algo = {path = "../algo"}
bincode = "1.3.3"
bitflags = "1.3.2"
euclid = "0.22.6"
log = "0.4.17"
lyon_algorithms = "0.17.7"
lyon_tessellation = {version = "0.17.0", features = ["serialization"]}
serde = {version = "1.0", features = ["rc"]}
text = {path = "../text"}
usvg = {version = "0.23.0", features = ["text"]}
