[package]
edition = "2021"
name = "ribir_painter"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ribir_algo = {path = "../algo"}
bitflags = "1.3.2"
euclid = "0.22.6"
log = "0.4.17"
lyon_algorithms = "1.0.1"
lyon_tessellation = {version = "1.0.1", features = ["serialization"]}
palette = {version = "0.6.1", features = ["serializing"]}
serde = {version = "1.0", features = ["rc"]}
serde_json = "1.0.82"
ribir_text = {path = "../text"}
usvg = {version = "0.23.0", features = ["text"]}
