[package]
categories = ["gui"]
description = "Ribir is a framework for building modern native/wasm cross-platform user interface applications."
documentation = "https://ribir.org/docs"
edition = "2021"
homepage = "https://ribir.org"
keywords = ["gui", "ui", "declarative", "compose-ui"]
license = "MIT"
name = "ribir_painter"
readme = "README.md"
repository = "https://github.com/RibirX/Ribir/algo"
version = "0.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.0.1"
bitflags-serde-legacy = "0.1.0"
euclid = {version = "0.22.6", features = ["serde"]}
log = "0.4.17"
lyon_algorithms = {version = "1.0.3", features = ["serialization"]}
lyon_tessellation = {version = "1.0.3", features = ["serialization"], optional = true}
palette = {version = "0.6.1", features = ["serializing"]}
rctree = "0.5.0"
ribir_algo = {path = "../algo", version = "0.0.0"}
ribir_text = {path = "../text", version = "0.0.0"}
serde = {version = "1.0", features = ["rc", "derive"]}
serde_json = "1.0.82"
tiny-skia-path = "0.8.3"
usvg = {version = "0.29.0"}
zerocopy = "0.6.1"

[features]
tessellation = ["lyon_tessellation"]
