[package]
edition = "2021"
name = "ribir_algo"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.3"
log = "0.4.14"
rayon = "1.5.1"
