[package]
edition = "2021"
name = "text"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
algo = {path = "../algo"}
arcstr = {version = "1.1.3", features = ["substr"]}
derive_more = "0.99.17"
fontdb = "0.7.0"
log = "0.4.14"
lyon_path = "0.17.7"
ordered-float = "2.10.0"
rustybuzz = "0.4.0"
ttf-parser = "0.12.3"
unicode-bidi = "0.3.7"
unicode-script = "0.5.4"
